### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by kitwoofer** [cdevseven/shephard-fixed-captions#1]
- [ ] Fix grammatical issues
- [x] Fix Shephard's name
- [x] Fix colors
- [ ] Add Japanese translation
- [ ] Episodes perhaps?
